module.exports = {
  routes: (models) => {
    const Joi = require('joi');
    const controllers = require('./auth.controllers')(models);

    return [
      {
        method: 'GET',
        path: '/auth/login',
        config: {
          auth: false,
          handler: controllers.getAuthLogin,
          description: 'Get an auth login',
          notes: 'Take this url and paste it in a new tab in your browser. It will take you to the login provider, where you will log in with the account you want an access code generated for. It will return you to the /auth/token url, where it should give you an access_token. Use this in the api_key box in the top right of the swagger docs.',
          tags: ['api', 'Auth'],
        }
      },
      {
        method: 'GET',
        path: '/auth/token',
        config: {
          auth: false,
          handler: controllers.getAuthToken,
          description: 'Get an auth token',
          notes: 'This endpoint is a return route for the url generated by /auth/login. It will parse the return url params, send the code back to the auth server to retrieve an access token.',
          validate: {
            query: Joi.object().keys({
              code: Joi.string().required(),
              state: Joi.string(),
              session_state: Joi.string(),
            })
          }
        }
      },
      {
        method: 'GET',
        path: '/auth/required',
        config: {
          auth: 'jwt',
          handler: controllers.getAuthRequired,
          description: 'Example auth required endpoint',
          notes: 'Returns true with a Response Code of 200 if user sends a valid authorization header',
          tags: ['api', 'Auth'],
        }
      },
    ];
  },
};
